services:
  # A Docker web service
  - type: web
    name: alist
    env: docker
    repo: https://github.com/Sadik084/alist-render # optional
    region: oregon # optional (defaults to oregon)
    plan: free # optional (defaults to starter)
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 5244
      - key: DB_TYPE
        value: MySQL
      - key: DB_HOST
        value: db4free.net
      - key: DB_PORT
        value: 3306
      - key: DB_USER
        value: servertechinfin
      - key: DB_PASS
        value: sadik@@@
      - key: DB_NAME
        value: techinfinities
      - key: DB_TABLE_PREFIX
        value: alist_
      - key: CDN
        value: https://npm.elemecdn.com/alist-web@$version/dist
